broadcast-town-creation: true
broadcast-town-deletion: true
teleport-timer: 5
add-spaces-to-town-name: false

colors:
  leader: "&c"
  admin: "&6"
  member: "&b"

messages:
  player-not-found: "&cPlayer not found!"
  not-player: "&cYou must be a player to run this command!"
  insufficient-perms: "&cInsufficient permissions!"
  incorrect-usage: "&cIncorrect usage! &e{usage}"
  already-in-team: "&cSei già in un team!"
  name-not-available: "&cTown name not available!"
  town-created: "&bYou created the town &e{town}&b!"
  town-created-broadcast: "&e{player} &bcreated the town &e{town}&b!"
  town-deleted: "&bYou deleted the town &e{town}&b!"
  town-deleted-broadcast: "&e{player} &b deleted the town &e{town}&b!"
  town-balance-chargeback: "&e{money} &badded to your balance from town bank!"
  not-in-town: "&cYou are not in a town!"
  not-leader: "&cYou must be the leader of the town to perform this command!"
  not-admin: "&cYou must be at least an admin to perform this command!"
  give-first: "&cYou are the leader of the town. Give the leader to someone else before leaving."
  player-invited: "&bYou invited &e{player} &bto your town."
  invite-received: "&bYou have been invited to &e{town} &bby &e{player}&b!\n&bType &e/town join <town> &bto accept the invite."
  no-invites: "&cYou don't have any invite!"
  invite-not-found: "&cInvite not found!"
  town-joined: "&bYou joined the town &e{town}&b!"
  player-joined-town: "&e{player} &bjoined your town!"
  not-in-your-town: "&cThis player is not in this town!"
  player-kicked: "&bYou kicked &e{player} from your town!"
  you-have-been-kicked: "&bYou have been kicked from &e{town}!"
  player-left: "&e{player} &bleft your town!"
  you-left: "&bYou left the town &e{town}&b!"
  tonw-give-failed: "&cTown give failed!"
  leader-transferred: "&bYou transferred the town leader role to &e{player}&b!"
  you-are-leader: "&bYou are now the leader of your town!"
  town-without-home: "&cYour town doesn't have an home!"
  teleport: "&bYou will be teleported in {time} seconds!"
  home-set: "&bHome set to &e{location}&b!"
  home-removed: "&bHome removed!"
  town-balance: "&bTown Balance: &e{balance}"
  cannot-deposit: "&cYou can't deposit money!"
  insufficient-money: "&cYou don't have enough money!"
  transaction-error: "&cSomething went wrong during your transaction!"
  deposit-success: "&e{money} &bdeposited to your town bank!\n&bTown Balance: &e{balance}"
  cannot-withdraw: "&cYou can't withdraw money!"
  insufficient-town-money: "&cYour town doesn't have enough money!"
  withdraw-success: "&e{money} &bwithdrew from your town bank!\n&bTown Balance: &e{balance}"
  town-not-found: "&cTown not found!"
  admin-promote: "&e{player} &bis now an admin!"
  admin-promote-target: "&bYou are now an admin of your town!"
  admin-demote: "&e{player} &bis now a simple member!"
  admin-demote-target: "&bYou are now a simple member of your town!"
  town-rename: "&bYour town is now known as &e{town}&b!"
  player-can-deposit: "&e{player} &bcan now deposit money to bank town!"
  player-cannot-deposit: "&e{player} &bcan't deposit anymore to bank town!"
  player-can-withdraw: "&e{player} &bcan now withdraw money from bank town!"
  player-cannot-withdraw: "&e{player} &bcan't withdraw anymore from bank town!"
  baltop-head: "&7&m------&e Towns &7&m------"
  baltop: "&e{position}. &b&l{town} &r- &e{balance}"
  baltop-footer: "&7&m------&e Towns &7&m------"

placeholders:
  none: "None"
  leader: "Leader"
  admin: "Admin"
  member: "Member"

town-chat: "&dTOWN: &6{player} &e>&r {message}"

town:
  - "&7&m----&r &e&l{town}&r &7&m----"
  - "&b&lBalance: &e{balance}"
  - "&b&lLeader: &e{leader}"
  - "&b&lAdmins: &e{admins}"
  - "&b&lMembers: &e{members}"

help:
  - "&7&m----&r &e&lTown Command&r &7&m----"
  - "&b/town baltop &f- &eshow the top 10 towns"
  - "&b/town create <name> &f- &eCreate a new town"
  - "&b/town delete &f- &eDelete your town"
  - "&b/town invite <player> &f- &eInvite a player to your town"
  - "&b/town join <name> &f- &eJoin a town if invited"
  - "&b/town kick <player> &f- &eKick a player from your town"
  - "&b/town leave &f- &eLeave your town"
  - "&b/town give <player> &f- &eTransfer the leader role to someone else"
  - "&b/town home &f- &eTeleport to the town home"
  - "&b/town sethome &f- &eSet the town home"
  - "&b/town delhome &f- &eDelete the town home"
  - "&b/town balance &f- &eSee the balance of the town bank"
  - "&b/town deposit <amount> &f- &eDeposit money to the town bank"
  - "&b/town withdraw <amount> &f- &eWithdraw money from the town bank"
  - "&b/town rename <name> &f- &eRename your town"
  - "&b/town user setAdmin <player> &f- &eMake a member admin of your town"
  - "&b/town user delAdmin <player> &f- &eMake an admin of your town a regular member"
  - "&b/town user deposit <player> allow &f- &eGrant the permission to deposit money"
  - "&b/town user deposit <player> deny &f- &eRevoke the permission to deposit money"
  - "&b/town user withdraw <player> allow &f- &eGrant the permission to withdraw money"
  - "&b/town user withdraw <player> deny &f- &eRevoke the permission to withdraw money"
  - "&b/townchat <message> &f- &eSend a message to all members of your town"
  - "&7&m----&r &e&lTown Command&r &7&m----"