name: ${project.name}
version: ${project.version}
main: network.multicore.vt.VanillaTowns
loader: network.multicore.vt.VanillaTownsLoader
api-version: 1.21
author: LoreScheffer
description: VanillaTowns
dependencies:
  server:
    Vault:
      load: BEFORE
      require: true
    PlaceholderAPI:
      load: BEFORE
      require: false
    Essentials:
      load: BEFORE
      require: false