name: ${project.name}
version: ${project.version}
main: it.multicoredev.vt.VanillaTowns
api-version: 1.13
author: LoreScheffer
description: VanillaTowns
depend: [Vault]
softdepend: [MVdWPlaceholderAPI]

commands:
  vanillatowns:
    aliases: [vt]
    description: Main plugin command
  town:
    aliases: [towns]
    description: Town command
  townchat:
    aliases: [tchat, tc]
    description: Town chat